export const resources = [
    {
        id: 1,
        title: "Budgeting 101",
        description: "Learn how to create and stick to a budget.",
        link: "https://money.usnews.com/money/personal-finance/saving-and-budgeting/articles/how-to-make-a-budget-and-stick-to-it",
        image: "/src/assets/budget.jpg",
    },
    {
        id: 2,
        title: "Understanding Credit Scores",
        description: "Find out what a credit score is and why it matters.",
        link: "https://getschooled.com/article/5787-teens-and-credit-scores/",
        image: "/src/assets/credit-score.jpg",
    },
    {
        id: 3,
        title: "How to Start Saving as Teen",
        description: "Learn the basics of saving money, setting financial goals, and building good habits.",
        link: "https://www.seventeen.com/life/school/a40670024/how-to-save-money-teenager/",
        image: "/src/assets/saving.jpg",
    },
    {
        id: 4,
        title: "Taxes 101 for Teens",
        description: "A beginner's guide to understanding taxes and why they matter.",
        link: "https://morganfranklinfoundation.org/taxes-for-teenagers/",
        image: "/src/assets/taxes.jpg",
    },
    {
        id: 5,
        title: "Intro to Investing",
        description: "Discover how investing works and why starting early can lead to big rewards.",
        link: "https://www.nerdwallet.com/article/investing/how-to-start-investing",
        image: "/src/assets/investing.jpg",
    },
    {
        id: 6,
        title: "How to Avoid Debt as a Teen",
        description: "Learn about the dangers of debt and how to make smart financial decisions.",
        link: "https://teensmeanbusiness.com/teenage-debt-and-how-to-avoid-it/",
        image: "/src/assets/debt.jpg",
      },
      {
        id: 7,
        title: "Best Credit Cards for Teens (2025)",
        description: "Let's dive into which cards are most appropriate for teens.",
        link: "https://www.cardrates.com/advice/best-credit-cards-for-teens/",
        image: "/src/assets/best-cards.jpg",
      },
      {
        id: 8,
        title: "Side Hustles for Teens",
        description: "Explore fun and easy ways to earn money as a teen.",
        link: "https://www.nichepursuits.com/side-hustles-for-teens/",
        image: "/src/assets/side-hustle.jpg",
      },
      {
        id: 9,
        title: "Understanding Financial Aid",
        description: "Learn about scholarships, grants, and loans to help pay for college.",
        link: "https://collegeaidpro.com/what-is-financial-aid/",
        image: "/src/assets/financial-aid.jpg",
      },
      {
        id: 10,
        title: "How to Spend Money Wisely",
        description: "Tips for making smart spending decisions and avoiding impulse buys.",
        link: "https://modernteen.co/money-management-tips-for-teenagers/",
        image: "/src/assets/spend-wisely.jpg",
      },
  ];